### ISSUE TITLE
Introduce support for the OriginalScore feature in LambdaMART model

### ISSUE THREAD

**Issue by alessandrobenedetti** [bloomberg/lucene-solr#10]
Currently the OriginalScore feature is not usable by a lambdaMART model.
I would suggest to add an additional param that will be as the SVM model params.

Just a scalar value and the originalScore feature.
In this way the final score coming from lambdaMart can be affected by the original score by the factor the user specified.

This will allow users to use LambdaMART models to boost documents, instead of completely re-write the score for them.
I will work on that and open a pull request.
We can discuss implications and ideas in the meantime.

**Comment by diegoceccarelli** [comment]
Reviewed and merged in the experimental branch
