### ISSUE TITLE
Feature vector caching Separation

### ISSUE THREAD

**Issue by alessandrobenedetti** [bloomberg/lucene-solr#172]
As we know we have different types of feature and they nature is different :

SolrFeature -> can be query dependent / query independent
FieldValueFeature -> query independent
ValueFeature -> query level
OriginalScoreFeature -> query dependent

**Intuition**
Let's see when the extracted value for feature change : 

**query independent ( document level features)** -> indexing time, every commit may change the feature value possibly and invalidate the cache entry .

query dependent -> both request parameters and index can change the feature value

query level -> only request parameters can change the value, completely not related to the index .

**Caching**
Let's see the benefits of having 3 separates cache ( so separating the feature vector components):

Query Independent Feature cache -> simply changing request parameters will not invalidate the cache entry, only a commit will cause the autowarming

Query Dependent Feature Cache -> this will behave like the current cache, so changing params you will cache a different feature vector.

Query level Cache -> the index is not involved at all 

I need to take a look to how caching works now to see if all I thought is actually feasible.

Cheers

**Comment by diegoceccarelli** [comment]
This is an interesting enhancement that we would like to implement, since we are closing the issues on Github, Alessandro will open an item on the Solr Jira board. Thanks @alessandrobenedetti !
