### ISSUE TITLE
LambdaMART explain summarization improvements

### ISSUE THREAD

**Issue by alessandrobenedetti** [bloomberg/lucene-solr#173]
The current explain for the lambdaMART model is quite nice and human readable.
But unfortunately when you have big ensemble of trees and  big trees, it becomes almost impossible to " explain why the document has that score" .

Scenario
LambdaMART model with 100 trees, each tree quite high.

We need also a summarized explain in my opinion.
This can be as smart as we want :

e.g.
Simple -> we fetch the features evaluated when scoring and we return the most occurring ones
Medium -> we return the most occurring features when scoring, highlighting the positive matches (go RIGHT for binary features can be more important)
Advanced - we order first the trees by how much they influenced the final score and we add this information to the summary weighting differently the features

This can be a game changer when explaining the score from a lambdaMART model, or at least can help :)

Cheers

**Comment by diegoceccarelli** [comment]
This is an interesting enhancement that we would like to implement, since we are closing the issues on Github, Alessandro will open an item on the Solr Jira board.
