### ISSUE TITLE
Sharded architecture / pagination problem

### ISSUE THREAD

**Issue by alessandrobenedetti** [bloomberg/lucene-solr#175]
As discussed previously, the pagination issues have been fixed for the single node.
But because the rescoring happens locally in each shard, I believe we have still problems with pagination in a shared environment.

Of course it is a minor issue that will appear only if you rerank few docs per shard or in deep pagination examples.

The problem resides in the fact that the aggregator of the results from the shards, will merge search results from different shards and then rank according to the score.
Each shard will return results in the proper order ( first reranked docs and following the original scored ones).
But score wise, rescored docs can have a smaller score than the original scored.

When the aggregation happens, original scored ones can surpass in the ranking the rescored ones.
I discussed briefly with Diego and his suggestion is to normalise the scores to make the re--ranked ones always with an higher score of the original scored.
I do agree this can be a possible solution to be consistent and maintain the ordinal nature of the score in Solr, that we are currently breaking at the reRankDocs point.

e.g.
reRankDocs=15
rows=10

This means each page is composed by 10 results.
What happens when we hit the page 2 ?
The first 5 documents in the search results will have been rescored and affected by the reranking.
The latter 5 documents will preserve the original score and original ranking.

e.g. Page 2
Doc 11 - score= 1.2
Doc 12 - score= 1.1
Doc 13 - score= 1.0
Doc 14 - score= 0.9
Doc 15 - score= 0.8
Doc 16 - score= 5.7   < -- we currently break the ordinal nature of score/ranking
Doc 17 - score= 5.6

**Comment by mnilsson23** [comment]
Yup, and this issue actually affects Solr's standard ReRankQuery as well.  The fix would have to be [somewhere here in the code](https://github.com/apache/lucene-solr/blob/a84d9a5d694e97c40d90a07a0882492946e72141/solr/core/src/java/org/apache/solr/search/ReRankCollector.java#L123).
An easy workaround right now would be to make sure that you set `reRankDocs` as a multiple of `rows` (20, 30, etc in the above example).  This way you never have a page with a mix of reranked and original ranked scores.

**Comment by alessandrobenedetti** [comment]
Yes Michael,
the issue is in the Solr out of the box rerank query as well :)

Actually even if you set the reRankDocs to be a multiple of rows the problem could appear still.
Let's see a simple example with 2 shards: 

e.g.
reRankDocs=10
rows=10
Shard number = 2

Page 2
As you have 2 shards, you reranked a total of 20 docs, so you would expect to see the page 2 to contain only reranked docs after the aggregation.
Correct me if I am wrong but when Solr aggregates it will take in consideration for the page 2 a total of 40 docs candidates :
Shard1 : 10 ReRanked docs ( page1) + 10 OriginalScored docs (page2)
Shard2 : 10 ReRanked docs (page1) + 10 OriginalScored docs (page2)

So the aggregated page 2 can actually contain even only original scored docs ( again for the reason the scores are not normalised and an original scored doc can be higher than a reranked one.

let me know if any of my assumptions are wrong, it has been a while I don't check the merge of sharded results for pagination :) 

Cheers

**Comment by alessandrobenedetti** [comment]
Also other funny things can happen, in the same scenario, for example in the page 2 you could see again some of the same documents that were in the page1 previously.

Because Original Scored could top up the re-ranked, and the re-ranked that were in the first page go down to the second page.

**Comment by mnilsson23** [comment]
Yup, good point, especially the funny thing about the document showing up again.

**Comment by diegoceccarelli** [comment]
This issue needs to be solved, Alessandro will open a new item on the Solr Jira board.
