### ISSUE TITLE
Bug: Not handling the case of unselecting the dismax option

### ISSUE THREAD

**Issue by faridasabry** [bloomberg/lucene-solr#2]
I received the below stack trace when I tried an example for learning to rank and added 'rq={!ltr model=myModelName reRankDocs=25}' to my query without enabling the the disjunction maximum option. After enabling it everything went ok but there are some irrelevant results added that didn't match before adding the ltr string to the query (trying to match _text_:25 and showing weight(_text_:25 in 180))??!!  changing reRankDocs=10 retrieves different irrelevant results and shows in the debug:  weight(_text_:10 .... if I choose  reRankDocs<10 only the four relevant results appear. But this should be another issue. 
java.lang.NullPointerException\n\tat org.apache.solr.ltr.ranking.ModelQuery.hashCode(ModelQuery.java:103)\n\tat org.apache.solr.ltr.ranking.LTRQuery.hashCode(LTRQuery.java:59)\n\tat java.util.HashMap.hash(HashMap.java:338)\n\tat java.util.HashMap.getOrDefault(HashMap.java:1048)\n\tat org.apache.lucene.search.Multiset.add(Multiset.java:84)\n\tat org.apache.lucene.search.BooleanQuery.<init>(BooleanQuery.java:168)\n\tat org.apache.lucene.search.BooleanQuery.<init>(BooleanQuery.java:41)\n\tat org.apache.lucene.search.BooleanQuery$Builder.build(BooleanQuery.java:145)\n\tat org.apache.solr.parser.SolrQueryParserBase.getBooleanQuery(SolrQueryParserBase.java:500)\n\tat org.apache.solr.parser.QueryParser.Query(QueryParser.java:146)\n\tat org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96)\n\tat org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:153)\n\tat org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50)\n\tat org.apache.solr.search.QParser.getQuery(QParser.java:141)\n\tat org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:162)\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:268)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:2033)\n\tat org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:652)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:229)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:184)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:518)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)\n\tat org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)\n\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)\n\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)\n\tat java.lang.Thread.run(Thread.java:745)\n",

**Comment by mnilsson23** [comment]
faridasabry, did you encounter this using the latest push in our release branch? Could you post a sample model + feature file that causes this problem?  I tried using the plugin without a dismax query (just used a '*:*' query and a simple 'field:foo' query) with a rerank rq:{!ltr ... } parameter and was not able to reproduce the problem you have above.  Some more context would be very helpful, thanks!

**Comment by faridasabry** [comment]
I was using another branch but I checked out the latest release branch and the same error occurred.

[model.json](<script src="https://gist.github.com/faridasabry/6bee4495811c528f144c6811798e2323.js"></script>) 

[audiofeatures.json](<script src="https://gist.github.com/faridasabry/1ea866baa9c5c5f47619b207fd7bbc77.js"></script>)

Screen shot for Solr:
https://www.dropbox.com/s/9l35i44whwl59oq/solr_screenshot.png?dl=0

**Comment by diegoceccarelli** [comment]
Hi @faridasabry, I tried to reproduce the bug without success, could you please try to rebuild solr with the latest version of the plugin (https://github.com/bloomberg/lucene-solr/tree/master-ltr-plugin-develop) and let us know if you still have the error? it could be that we already solved that issue.. Thank you.

**Comment by mnilsson23** [comment]
Hey @faridasabry,, I also noticed in your screenshot that you are getting the Model does not exist error.  Did you remember to [deploy your model](https://github.com/bloomberg/lucene-solr/tree/master-ltr-plugin-develop/solr/contrib/ltr#deploy-models-and-features)?  Don't forget to replace the collection1 name with your collection.

**Comment by diegoceccarelli** [comment]
@faridasabry we were not able to reproduce the issue, please if it still happens with current version of ltr in [Solr](https://github.com/apache/lucene-solr) open a bug item in the [Solr Jira board](https://issues.apache.org/jira/browse/SOLR/)
