### ISSUE TITLE
Expose a parameter to return dense features in the response

### ISSUE THREAD

**Issue by mnilsson23** [bloomberg/lucene-solr#20]
Currently when extracting features with the transformer, you get back the features that apply per doc in a sparse format.  This ticket is to add an option to return the feature vector in a dense format as well for ease of use for those that want it.  
Disclaimer though, returning dense feature vectors will increase the amount of data that is transported back in the response, potentially impacting performance based on how many features you are extracting.

**Comment by jdorando** [comment]
This can be closed. It was completed in https://github.com/bloomberg/lucene-solr/pull/56
