### ISSUE TITLE
How to train the model using user clicks? 

### ISSUE THREAD

**Issue by jefferyyuan** [bloomberg/lucene-solr#207]
Thanks very much for integrating machine learning to Solr.

In the Assemble training data part: the third column indicates the relative importance or relevance of that doc
Could you please give more info about how to give a score based on what user clicks?

I read https://static.aminer.org/pdf/PDF/000/472/865/optimizing_search_engines_using_clickthrough_data.pdf
http://www.cs.cornell.edu/people/tj/publications/joachims_etal_05a.pdf
But still have no clue how to translate the partial pairwise feedback to the importance or relevance of that doc.

Thanks again for your help.

**Comment by diegoceccarelli** [comment]
Resolved in https://issues.apache.org/jira/browse/SOLR-9929
