### ISSUE TITLE
Reuse code in LTRRescorer in LTRTransformer

### ISSUE THREAD

**Issue by diegoceccarelli** [bloomberg/lucene-solr#25]
The LTRRescorer and the Transformer both do very similar things to calculate the score and feature values. They should reuse code where possible with some helper function so we don't have to make changes in 2 places when dealing with query-weight-scorer-doc calculations.

**Comment by mnilsson23** [comment]
Refactoring happened in a few commits

**Comment by cpoerschke** [comment]
#138 and #139 would be the last parts of the refactor.
